services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: wwssdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5174:5432"
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - "5175:8080"
