services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=wwssdb'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=rootpassword'
      - 'MYSQL_USER=admin'
    ports:
      - '5174:3306'
    restart: always
