services:
  db:
    image: 'postgres'
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=wwssdb
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=admin
    ports:
      - '5174:5432'
    volumes:
      - './store/.db:/var/lib/postgresql'

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    restart: always
    ports:
      - "5175:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://admin:secret@db:5432/wwssdb?sslmode=disable
    depends_on:
      - db
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    tty: true
    ports:
      - '5176:5678'
    environment:
      - GENERIC_TIMEZONE="America/Toronto"
      - TZ="America/Toronto"
      - N8N_RUNNERS_ENABLED=true
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=admin
      - DB_POSTGRESDB_PASSWORD=secret
    # Persist n8n runtime data and appdata on the host
    volumes:
      - './store/.n8n:/home/node/.n8n'
    depends_on:
      - db
      - pgweb
  comfyui-boot:
    stdin_open: true
    tty: true
    container_name: comfyui-cu124
    ports:
      - 8147:8188
    volumes:
      - './store/ComfyUI:/root'
    image: yanwk/comfyui-boot:cu124-slim
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu